name: cobo_lab
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.12
  - pandas
  - plotly
  - matplotlib
  - seaborn
  - openpyxl
  - scikit-learn
  - scipy
  - numpy
  - biopython   # Required for BLAST searches
  - requests    # Needed for API calls to NCBI
  - nbformat